from tkinter import *
import os
import random


def get_file(folder,pic):
    scr_name = os.path.dirname(__file__)
    sep = "\\"
    if not os.name == "nt":
        sep = "/"
    name = scr_name + sep + folder + sep+ pic
    return name

def tk_run():
    root = Tk()
    root.title("GUI")
    root.geometry("1920x1080")
    root.iconbitmap('')


    root_file = os.path.dirname(__file__)
    
    sep = "\\"

    if not os.name == "nt":
        sep = "/"

    y120 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"120.png"))
    y119 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"119.png"))
    y118 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"118.png"))
    y117 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"117.png"))
    y116 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"116.png"))
    y115 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"115.png"))
    y114 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"114.png"))
    y113 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"113.png"))
    y112 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"112.png"))
    y111 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"111.png"))
    y110 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"110.png"))
    y109 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"109.png"))
    y108 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"108.png"))
    y107 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"107.png"))
    y106 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"106.png"))
    y105 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"105.png"))
    y104 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"104.png"))
    y103 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"103.png"))
    y102 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"102.png"))
    y101 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"101.png"))
    y100 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"100.png"))
    y99 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"99.png"))
    y98 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"98.png"))
    y97 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"97.png"))
    y96 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"96.png"))
    y95 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"95.png"))
    y94 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"94.png"))
    y93 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"93.png"))
    y92 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"92.png"))
    y91 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"91.png"))
    y90 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"90.png"))
    y89 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"89.png"))
    y88 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"88.png"))
    y87 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"87.png"))
    y86 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"86.png"))
    y85 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"85.png"))
    y84 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"84.png"))
    y83 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"83.png"))
    y82 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"82.png"))
    y81 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"81.png"))
    y80 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"80.png"))
   #
    y79 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"79.png"))
    y78 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"78.png"))
    y77 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"77.png"))
    y75 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"75.png"))
    y74 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"74.png"))
    y73 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"73.png"))
    y72 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"72.png"))
    y71 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"71.png"))
    y70 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"70.png"))
    #
    y69 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"69.png"))
    y68 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"68.png"))
    y67 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"67.png"))
    y66 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"66.png"))
    y65 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"65.png"))
    y64 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"64.png"))
    y63 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"63.png"))
    y62 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"62.png"))
    y61 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"61.png"))
    y60 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"60.png"))
    y59 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"59.png"))
    y58 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"58.png"))
    y57 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"57.png"))
    y56 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"56.png"))
    y55 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"55.png"))
    y54 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"54.png"))
    y53 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"53.png"))
    y52 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"52.png"))
    y51 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"51.png"))
    y50 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"50.png"))
    #
    y49 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"49.png"))
    y48 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"48.png"))
    y47 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"47.png"))
    y46 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"46.png"))
    y45 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"45.png"))
    y44 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"44.png"))
    y43 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"43.png"))
    y42 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"42.png"))
    y41 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"41.png"))
    y40 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"40.png"))
    #
    y39 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"39.png"))
    y38 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"38.png"))
    y37 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"37.png"))
    y36 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"36.png"))
    y35 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"35.png"))
    y34 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"34.png"))
    y33 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"33.png"))
    y32 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"32.png"))
    y31 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"31.png"))
    y30 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"30.png"))
    #
    y29 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"29.png"))
    y28 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"28.png"))
    y27 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"27.png"))
    y26 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"21.png"))
    y25 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"25.png"))
    y24 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"24.png"))
    y23 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"23.png"))
    y22 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"22.png"))
    y21 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"21.png"))
    y20 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"20.png"))
    #
    y19 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"19.png"))
    y18 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"18.png"))
    y17 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"17.png"))
    y11 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"11.png"))
    y15 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"15.png"))
    y14 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"14.png"))
    y13 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"13.png"))
    y12 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"12.png"))
    y11 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"11.png"))
    y10 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"10.png"))
    #
    y9 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"9.png"))
    y8 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"8.png"))
    y7 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"7.png"))
    y6 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"6.png"))
    y5 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"5.png"))
    y4 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"4.png"))
    y3 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"3.png"))
    y2 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"2.png"))
    y1 = PhotoImage(file=get_file("full_clean_ocean_fixed" ,"1.png"))
    

    #--------------------------

    x120 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"120.png"))
    x119 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"119.png"))
    x118 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"118.png"))
    x117 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"117.png"))
    x116 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"116.png"))
    x115 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"115.png"))
    x114 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"114.png"))
    x113 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"113.png"))
    x112 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"112.png"))
    x111 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"111.png"))
    x110 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"110.png"))
    x109 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"109.png"))
    #-
    x108 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"108.png"))
    x107 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"107.png"))
    x106 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"106.png"))
    x105 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"105.png"))
    x104 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"104.png"))
    x103 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"103.png"))
    x102 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"102.png"))
    x101 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"101.png"))
    x100 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"100.png"))
    x99 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"99.png"))
    x98 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"98.png"))
    x97 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"97.png"))
    #-
    x96 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"96.png"))
    x95 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"95.png"))
    x94 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"94.png"))
    x93 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"93.png"))
    x92 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"92.png"))
    x91 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"91.png"))
    x90 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"90.png"))
    x89 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"89.png"))
    x88 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"88.png"))
    x87 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"87.png"))
    x86 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"86.png"))
    x85 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"85.png"))
    #-
    x84 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"84.png"))
    x83 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"83.png"))
    x82 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"82.png"))
    x81 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"81.png"))
    x80 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"80.png"))
    x79 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"79.png"))
    x78 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"78.png"))
    x77 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"77.png"))
    x76 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"76.png"))
    x75 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"75.png"))
    x74 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"74.png"))
    x73 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"73.png"))
    #-
    x72 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"72.png"))
    x71 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"71.png"))
    x70 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"70.png"))
    x69 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"69.png"))
    x68 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"68.png"))
    x67 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"67.png"))
    x66 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"66.png"))
    x65 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"65.png"))
    x64 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"64.png"))
    x63 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"63.png"))
    x62 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"62.png"))
    x61 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"61.png"))
    #-
    x60 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"60.png"))
    x59 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"59.png"))
    x58 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"58.png"))
    x57 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"57.png"))
    x56 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"56.png"))
    x55 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"55.png"))
    x54 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"54.png"))
    x53 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"53.png"))
    x52 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"52.png"))
    x51 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"51.png"))
    x50 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"50.png"))
    x49 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"49.png"))
    #-
    x48 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"48.png"))
    x47 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"47.png"))
    x46 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"46.png"))
    x45 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"45.png"))
    x44 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"44.png"))
    x43 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"43.png"))
    x42 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"42.png"))
    x41 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"41.png"))
    x40 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"40.png"))
    x39 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"39.png"))
    x38 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"38.png"))
    x37 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"37.png"))
    #-
    x36 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"36.png"))
    x35 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"35.png"))
    x34 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"34.png"))
    x33 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"33.png"))
    x32 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"32.png"))
    x31 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"31.png"))
    x30 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"30.png"))
    x29 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"29.png"))
    x28 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"28.png"))
    x27 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"27.png"))
    x26 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"26.png"))
    x25 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"25.png"))
    #-
    x24 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"24.png"))
    x23 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"23.png"))
    x22 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"22.png"))
    x21 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"21.png"))
    x20 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"20.png"))
    x19 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"19.png"))
    x18 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"18.png"))
    x17 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"17.png"))
    x16 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"16.png"))
    x15 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"15.png"))
    x14 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"14.png"))
    x13 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"13.png"))
   #-
    x12 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"12.png"))
    x11 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"11.png"))
    x10 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"10.png"))
    x9 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"9.png"))
    x8 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"8.png"))
    x7 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"7.png"))
    x6 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"6.png"))
    x5 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"5.png"))
    x4 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"4.png"))
    x3 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"3.png"))
    x2 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"2.png"))
    x1 = PhotoImage(file=get_file("full_dirty_puzzle_fixed" ,"1.png"))
   

    footwear = PhotoImage(file=root_file + sep +"footwear.png")
    plastic_bottle = PhotoImage(file=root_file +  sep +"plastic-bottle.png")
    coin = PhotoImage(file=root_file + sep + "coin.png")
    bottle_cap=PhotoImage(file=root_file + sep +"bottle-cap.png")
    cigarette = PhotoImage(file=root_file + sep +"cigarette.png")
    glass_bottle = PhotoImage(file=root_file + sep +"glass-bottle.png")
    wrapper = PhotoImage(file=root_file + sep +"wrapper.png")
    plastic_bag = PhotoImage(file=root_file + sep +"plastic-bag.png")
    can = PhotoImage(file=root_file + sep +"can.png")

    footwear_pos = [x63, x72, x97, x102, x103]
    plastic_bottle_pos = [x69, x66, x84, x83, x118, x114]
    coin_pos = [x120]
    bottle_cap_pos = [x68, x83, x74, x77, x93, x99, x107, x119, x115]
    cigarette_pos = [x62, x63, x65, x67, x73, x75, x80, x82, x85, x87, x91, x95, x100, x106, x110, x111, x114]
   
    wrapper=[x2,x4,x10,x12,x14,x22,x29,x33,x35] 
    can = [x13,x32,x35,x41]
    plastic_bag=[x8,x4,x16,x17,x19,x23,x27,x31,x33,x41,x44,x46,x47,x48,x51]
    glass_bottle=[x16,x27,x38,x60]
    
    dirt = ["footwear","plastic_bag","coin","bottle_cap","can","cigarette","plastic_bottle","glass_bottle","wrappers"]
    dirt_images = [footwear,plastic_bag,coin,bottle_cap,cigarette,plastic_bottle,glass_bottle,can,wrapper]
    picked_dirt=random.choice(dirt_images)
   
    itemname = Label(root,text = str(picked_dirt),font = ("courier new",30))
    itemname.place(x=875,y=10)

    imagelabel = Label(root, image=picked_dirt)
    imagelabel.place(x=975,y=60)

    raritylabel = Label(root,text = "RARITY WILL GO HERE",font = ("courier new",20))
    raritylabel.place(x=875, y=200)

    infolabel = Label(root,text = "INFO WILL GO HERE",font = ("courier new",10))
    infolabel.place(x=950, y=275)
    
    sky = PhotoImage(file=root_file+"{}full_clean_ocean.png".format(sep))
    

    bt120 = Button(root,bd=0,image = x120)
    bt120.place(x=10,y=0)
    bt119 = Button(root,bd=0,image = x119)
    bt119.place(x=75,y=0)    
    bt118 = Button(root,bd=0,image = x118)
    bt118.place(x=140,y=0)
    bt117 = Button(root,bd=0,image = x117)
    bt117.place(x=205,y=0)    
    bt116 = Button(root,bd=0,image = x116)
    bt116.place(x=270,y=0)
    bt115 = Button(root,bd=0,image = x115)
    bt115.place(x=335,y=0)    
    bt114 = Button(root,bd=0,image = x114)
    bt114.place(x=400,y=0)
    bt113 = Button(root,bd=0,image = x113)
    bt113.place(x=465,y=0)  
    bt112 = Button(root,bd=0,image = x112)
    bt112.place(x=530,y=0)
    bt111 = Button(root,bd=0,image = x111)
    bt111.place(x=595,y=0)    
    bt110 = Button(root,bd=0,image = x110)
    bt110.place(x=660,y=0)
    bt109 = Button(root,bd=0,image = x109)
    bt109.place(x=725,y=0)   
    #-
    bt108 = Button(root,bd=0,image = x108)
    bt108.place(x=10,y=65)  
    bt107 = Button(root,bd=0,image = x107)
    bt107.place(x=75,y=65)    
    bt106 = Button(root,bd=0,image = x106)
    bt106.place(x=140,y=65)
    bt105 = Button(root,bd=0,image = x105)
    bt105.place(x=205,y=65)    
    bt104 = Button(root,bd=0,image = x104)
    bt104.place(x=270,y=65)
    bt103 = Button(root,bd=0,image = x103)
    bt103.place(x=335,y=65)    
    bt102 = Button(root,bd=0,image = x102)
    bt102.place(x=400,y=65)
    bt101 = Button(root,bd=0,image = x101)
    bt101.place(x=465,y=65)  
    bt100 = Button(root,bd=0,image = x100)
    bt100.place(x=530,y=65)
    bt99 = Button(root,bd=0,image = x99)
    bt99.place(x=595,y=65)    
    bt98 = Button(root,bd=0,image = x98)
    bt98.place(x=660,y=65)
    bt97 = Button(root,bd=0,image = x97)
    bt97.place(x=725,y=65)   
    #-
    bt96 = Button(root,bd=0,image = x96)
    bt96.place(x=10,y=130)
    bt95 = Button(root,bd=0,image = x95)
    bt95.place(x=75,y=130)    
    bt94 = Button(root,bd=0,image = x94)
    bt94.place(x=140,y=130)
    bt93 = Button(root,bd=0,image = x93)
    bt93.place(x=205,y=130)    
    bt92 = Button(root,bd=0,image = x92)
    bt92.place(x=270,y=130)
    bt91 = Button(root,bd=0,image = x91)
    bt91.place(x=335,y=130)    
    bt90 = Button(root,bd=0,image = x90)
    bt90.place(x=400,y=130)
    bt89 = Button(root,bd=0,image = x89)
    bt89.place(x=465,y=130)  
    bt88 = Button(root,bd=0,image = x88)
    bt88.place(x=530,y=130)
    bt87 = Button(root,bd=0,image = x87)
    bt87.place(x=595,y=130)    
    bt86 = Button(root,bd=0,image = x86)
    bt86.place(x=660,y=130)
    bt85 = Button(root,bd=0,image = x85)
    bt85.place(x=725,y=130)   
    #-
    bt84 = Button(root,bd=0,image = x84)
    bt84.place(x=10,y=195)
    bt83 = Button(root,bd=0,image = x83)
    bt83.place(x=75,y=195)    
    bt82 = Button(root,bd=0,image = x82)
    bt82.place(x=140,y=195)
    bt81 = Button(root,bd=0,image = x81)
    bt81.place(x=205,y=195)    
    bt80 = Button(root,bd=0,image = x80)
    bt80.place(x=270,y=195)
    bt79 = Button(root,bd=0,image = x79)
    bt79.place(x=335,y=195)    
    bt78 = Button(root,bd=0,image = x78)
    bt78.place(x=400,y=195)
    bt77 = Button(root,bd=0,image = x77)
    bt77.place(x=465,y=195)  
    bt76 = Button(root,bd=0,image = x76)
    bt76.place(x=530,y=195)
    bt75 = Button(root,bd=0,image = x75)
    bt75.place(x=595,y=195)    
    bt74 = Button(root,bd=0,image = x74)
    bt74.place(x=660,y=195)
    bt73 = Button(root,bd=0,image = x73)
    bt73.place(x=725,y=195)   
   #-
    bt72 = Button(root,bd=0,image = x72)
    bt72.place(x=10,y=260)
    bt71 = Button(root,bd=0,image = x71)
    bt71.place(x=75,y=260)    
    bt70 = Button(root,bd=0,image = x70)
    bt70.place(x=140,y=260)
    bt69 = Button(root,bd=0,image = x69)
    bt69.place(x=205,y=260)    
    bt68 = Button(root,bd=0,image = x68)
    bt68.place(x=270,y=260)
    bt67 = Button(root,bd=0,image = x67)
    bt67.place(x=335,y=260)    
    bt66 = Button(root,bd=0,image = x66)
    bt66.place(x=400,y=260)
    bt65 = Button(root,bd=0,image = x65)
    bt65.place(x=465,y=260)  
    bt64 = Button(root,bd=0,image = x64)
    bt64.place(x=530,y=260)
    bt63 = Button(root,bd=0,image = x63)
    bt63.place(x=595,y=260)    
    bt62 = Button(root,bd=0,image = x62)
    bt62.place(x=660,y=260)
    bt61 = Button(root,bd=0,image = x61)
    bt61.place(x=725,y=260)    
#-
    bt60 = Button(root,bd=0,image = x60)
    bt60.place(x=10,y=325)
    bt59 = Button(root,bd=0,image = x59)
    bt59.place(x=75,y=325)    
    bt58 = Button(root,bd=0,image = x58)
    bt58.place(x=140,y=325)
    bt57 = Button(root,bd=0,image = x57)
    bt57.place(x=205,y=325)    
    bt56 = Button(root,bd=0,image = x56)
    bt56.place(x=270,y=325)
    bt55 = Button(root,bd=0,image = x55)
    bt55.place(x=335,y=325)   
    bt54 = Button(root,bd=0,image = x54)
    bt54.place(x=400,y=325)
    bt53 = Button(root,bd=0,image = x53)
    bt53.place(x=465,y=325)  
    bt52 = Button(root,bd=0,image = x52)
    bt52.place(x=530,y=325)
    bt51 = Button(root,bd=0,image = x51)
    bt51.place(x=595,y=325)    
    bt50 = Button(root,bd=0,image = x50)
    bt50.place(x=660,y=325)
    bt49 = Button(root,bd=0,image = x49)
    bt49.place(x=725,y=325)    
#-
    bt48 = Button(root,bd=0,image = x48)
    bt48.place(x=10,y=390)
    bt47 = Button(root,bd=0,image = x47)
    bt47.place(x=75,y=390)  
    bt46 = Button(root,bd=0,image = x46)
    bt46.place(x=140,y=390)
    bt45 = Button(root,bd=0,image = x45)
    bt45.place(x=205,y=390)    
    bt44 = Button(root,bd=0,image = x44)
    bt44.place(x=270,y=390)
    bt43 = Button(root,bd=0,image = x43)
    bt43.place(x=335,y=390)   
    bt42 = Button(root,bd=0,image = x42)
    bt42.place(x=400,y=390)
    bt41 = Button(root,bd=0,image = x41)
    bt41.place(x=465,y=390)  
    bt40 = Button(root,bd=0,image = x40)
    bt40.place(x=530,y=390)
    bt39 = Button(root,bd=0,image = x39)
    bt39.place(x=595,y=390)    
    bt38 = Button(root,bd=0,image = x38)
    bt38.place(x=660,y=390)
    bt37 = Button(root,bd=0,image = x37)
    bt37.place(x=725,y=390)    
#-
    bt36 = Button(root,bd=0,image = x36)
    bt36.place(x=10,y=455)
    bt35 = Button(root,bd=0,image = x35)
    bt35.place(x=75,y=455)    
    bt34 = Button(root,bd=0,image = x34)
    bt34.place(x=140,y=455)
    bt33 = Button(root,bd=0,image = x33)
    bt33.place(x=205,y=455)    
    bt32 = Button(root,bd=0,image = x32)
    bt32.place(x=270,y=455)
    bt31 = Button(root,bd=0,image = x31)
    bt31.place(x=335,y=455)   
    bt30 = Button(root,bd=0,image = x30)
    bt30.place(x=400,y=455)
    bt29 = Button(root,bd=0,image = x29)
    bt29.place(x=465,y=455)  
    bt28 = Button(root,bd=0,image = x28)
    bt28.place(x=530,y=455)
    bt27 = Button(root,bd=0,image = x27)
    bt27.place(x=595,y=455)    
    bt26 = Button(root,bd=0,image = x26)
    bt26.place(x=660,y=455)
    bt25 = Button(root,bd=0,image = x25)
    bt25.place(x=725,y=455)    
    #-
    bt24 = Button(root,bd=0,image = x24)
    bt24.place(x=10,y=520)
    bt23 = Button(root,bd=0,image = x23)
    bt23.place(x=75,y=520)    
    bt22 = Button(root,bd=0,image = x22)
    bt22.place(x=140,y=520)
    bt21 = Button(root,bd=0,image = x21)
    bt21.place(x=205,y=520)    
    bt20 = Button(root,bd=0,image = x20)
    bt20.place(x=270,y=520)
    bt19 = Button(root,bd=0,image = x19)
    bt19.place(x=335,y=520)   
    bt18 = Button(root,bd=0,image = x18)
    bt18.place(x=400,y=520)
    bt17 = Button(root,bd=0,image = x17)
    bt17.place(x=465,y=520)  
    bt16 = Button(root,bd=0,image = x16)
    bt16.place(x=530,y=520)
    bt15 = Button(root,bd=0,image = x15)
    bt15.place(x=595,y=520)    
    bt14 = Button(root,bd=0,image = x14)
    bt14.place(x=660,y=520)
    bt13 = Button(root,bd=0,image = x13)
    bt13.place(x=725,y=520)    
#-
    bt12 = Button(root,bd=0,image = x12)
    bt12.place(x=10,y=585)
    bt11 = Button(root,bd=0,image = x11)
    bt11.place(x=75,y=585)    
    bt10 = Button(root,bd=0,image = x10)
    bt10.place(x=140,y=585)
    bt9 = Button(root,bd=0,image = x9)
    bt9.place(x=205,y=585)    
    bt8 = Button(root,bd=0,image = x8)
    bt8.place(x=270,y=585)
    bt7 = Button(root,bd=0,image = x7)
    bt7.place(x=335,y=585)   
    bt6 = Button(root,bd=0,image = x6)
    bt6.place(x=400,y=585)
    bt5 = Button(root,bd=0,image = x5)
    bt5.place(x=465,y=585)  
    bt4 = Button(root,bd=0,image = x4)
    bt4.place(x=530,y=585)
    bt3 = Button(root,bd=0,image = x3)
    bt3.place(x=595,y=585)    
    bt2 = Button(root,bd=0,image = x2)
    bt2.place(x=660,y=585)
    bt1 = Button(root,bd=0,image = x1)
    bt1.place(x=725,y=585)      


    
    
    root.mainloop()