from tkinter import *
import os

def tk_run():
    root = Tk()
    root.title("GUI")
    root.geometry("1980x1080")
    root.iconbitmap('')

    x120 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\120.png")
    x119 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\119.png")
    x118 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\118.png")
    x117 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\117.png")
    x116 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\116.png")
    x115 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\115.png")
    x114 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\114.png")
    x113 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\113.png")
    x112 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\112.png")
    x111 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\111.png")
    x110 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\110.png")
    x109 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\109.png")
    #-
    x108 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\108.png")
    x107 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\107.png")
    x106 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\106.png")
    x105 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\105.png")
    x104 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\104.png")
    x103 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\103.png")
    x102 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\102.png")
    x101 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\101.png")
    x100 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\100.png")
    x99 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\99.png")
    x98 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\98.png")
    x97 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\97.png")
    #-
    x96 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\96.png")
    x95 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\95.png")
    x94 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\94.png")
    x93 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\93.png")
    x92 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\92.png")
    x91 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\91.png")
    x90 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\90.png")
    x89 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\89.png")
    x88 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\88.png")
    x87 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\87.png")
    x86 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\86.png")
    x85 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\85.png")
    #-
    x84 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\84.png")
    x83 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\83.png")
    x82 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\82.png")
    x81 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\81.png")
    x80 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\80.png")
    x79 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\79.png")
    x78 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\78.png")
    x77 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\77.png")
    x76 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\76.png")
    x75 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\75.png")
    x74 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\74.png")
    x73 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\73.png")
    #-
    x72 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\72.png")
    x71 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\71.png")
    x70 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\70.png")
    x69 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\69.png")
    x68 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\68.png")
    x67 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\67.png")
    x66 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\66.png")
    x65 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\65.png")
    x64 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\64.png")
    x63 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\63.png")
    x62 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\62.png")
    x61 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\61.png")
    #-
    x60 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\60.png")
    x59 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\59.png")
    x58 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\58.png")
    x57 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\57.png")
    x56 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\56.png")
    x55 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\55.png")
    x54 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\54.png")
    x53 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\53.png")
    x52 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\52.png")
    x51 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\51.png")
    x50 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\50.png")
    x49 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\49.png")
    #-
    x48 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\48.png")
    x47 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\47.png")
    x46 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\46.png")
    x45 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\45.png")
    x44 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\44.png")
    x43 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\43.png")
    x42 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\42.png")
    x41 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\41.png")
    x40 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\40.png")
    x39 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\39.png")
    x38 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\38.png")
    x37 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\37.png")
    #-
    x36 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\36.png")
    x35 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\35.png")
    x34 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\34.png")
    x33 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\33.png")
    x32 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\32.png")
    x31 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\31.png")
    x30 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\30.png")
    x29 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\29.png")
    x28 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\28.png")
    x27 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\27.png")
    x26 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\26.png")
    x25 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\25.png")
    #-
    x24 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\24.png")
    x23 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\23.png")
    x22 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\22.png")
    x21 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\21.png")
    x20 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\20.png")
    x19 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\19.png")
    x18 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\18.png")
    x17 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\17.png")
    x16 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\16.png")
    x15 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\15.png")
    x14 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\14.png")
    x13 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\13.png")
   #-
    x12 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\12.png")
    x11 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\11.png")
    x10 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\10.png")
    x9 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\9.png")
    x8 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\8.png")
    x7 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\7.png")
    x6 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\6.png")
    x5 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\5.png")
    x4 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\4.png")
    x3 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\3.png")
    x2 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\2.png")
    x1 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\1.png")
   
   
   
   

    itemname = Label(root,text = "lols",font = ("courier new",30))
    itemname.place(x=1000,y=10)
    
    root_file = os.path.dirname(__file__)
    
    seprator = "\\"

    if not os.name == "nt":
        seprator = "/"


    sky = PhotoImage(file=root_file+"{}full_clean_ocean.png".format(seprator))
    

    bt120 = Button(root,bd=0,image = x120)
    bt120.place(x=10,y=10)
    bt119 = Button(root,bd=0,image = x119)
    bt119.place(x=75,y=10)    
    bt118 = Button(root,bd=0,image = x118)
    bt118.place(x=140,y=10)
    bt117 = Button(root,bd=0,image = x117)
    bt117.place(x=205,y=10)    
    bt116 = Button(root,bd=0,image = x116)
    bt116.place(x=270,y=10)
    bt115 = Button(root,bd=0,image = x115)
    bt115.place(x=335,y=10)    
    bt114 = Button(root,bd=0,image = x114)
    bt114.place(x=400,y=10)
    bt113 = Button(root,bd=0,image = x113)
    bt113.place(x=465,y=10)  
    bt112 = Button(root,bd=0,image = x112)
    bt112.place(x=530,y=10)
    bt111 = Button(root,bd=0,image = x111)
    bt111.place(x=595,y=10)    
    bt110 = Button(root,bd=0,image = x110)
    bt110.place(x=660,y=10)
    bt109 = Button(root,bd=0,image = x109)
    bt109.place(x=725,y=10)   
    #-
    bt108 = Button(root,bd=0,image = x108)
    bt108.place(x=10,y=75)
    bt107 = Button(root,bd=0,image = x107)
    bt107.place(x=75,y=75)    
    bt106 = Button(root,bd=0,image = x106)
    bt106.place(x=140,y=75)
    bt105 = Button(root,bd=0,image = x105)
    bt105.place(x=205,y=75)    
    bt104 = Button(root,bd=0,image = x104)
    bt104.place(x=270,y=75)
    bt103 = Button(root,bd=0,image = x103)
    bt103.place(x=335,y=75)    
    bt102 = Button(root,bd=0,image = x102)
    bt102.place(x=400,y=75)
    bt101 = Button(root,bd=0,image = x101)
    bt101.place(x=465,y=75)  
    bt100 = Button(root,bd=0,image = x100)
    bt100.place(x=530,y=75)
    bt99 = Button(root,bd=0,image = x99)
    bt99.place(x=595,y=75)    
    bt98 = Button(root,bd=0,image = x98)
    bt98.place(x=660,y=75)
    bt97 = Button(root,bd=0,image = x97)
    bt97.place(x=725,y=75)   
    #-
    bt96 = Button(root,bd=0,image = x96)
    bt96.place(x=10,y=140)
    bt95 = Button(root,bd=0,image = x95)
    bt95.place(x=75,y=140)    
    bt94 = Button(root,bd=0,image = x94)
    bt94.place(x=140,y=140)
    bt93 = Button(root,bd=0,image = x93)
    bt93.place(x=205,y=140)    
    bt92 = Button(root,bd=0,image = x92)
    bt92.place(x=270,y=140)
    bt91 = Button(root,bd=0,image = x91)
    bt91.place(x=335,y=140)    
    bt90 = Button(root,bd=0,image = x90)
    bt90.place(x=400,y=140)
    bt89 = Button(root,bd=0,image = x89)
    bt89.place(x=465,y=140)  
    bt88 = Button(root,bd=0,image = x88)
    bt88.place(x=530,y=140)
    bt87 = Button(root,bd=0,image = x87)
    bt87.place(x=595,y=140)    
    bt86 = Button(root,bd=0,image = x86)
    bt86.place(x=660,y=140)
    bt85 = Button(root,bd=0,image = x85)
    bt85.place(x=725,y=140)   
    #-
    bt84 = Button(root,bd=0,image = x84)
    bt84.place(x=10,y=205)
    bt83 = Button(root,bd=0,image = x83)
    bt83.place(x=75,y=205)    
    bt82 = Button(root,bd=0,image = x82)
    bt82.place(x=140,y=205)
    bt81 = Button(root,bd=0,image = x81)
    bt81.place(x=205,y=205)    
    bt80 = Button(root,bd=0,image = x80)
    bt80.place(x=270,y=205)
    bt79 = Button(root,bd=0,image = x79)
    bt79.place(x=335,y=205)    
    bt78 = Button(root,bd=0,image = x78)
    bt78.place(x=400,y=205)
    bt77 = Button(root,bd=0,image = x77)
    bt77.place(x=465,y=205)  
    bt76 = Button(root,bd=0,image = x76)
    bt76.place(x=530,y=205)
    bt75 = Button(root,bd=0,image = x75)
    bt75.place(x=595,y=205)    
    bt74 = Button(root,bd=0,image = x74)
    bt74.place(x=660,y=205)
    bt73 = Button(root,bd=0,image = x73)
    bt73.place(x=725,y=205)   
   #-
    bt72 = Button(root,bd=0,image = x72)
    bt72.place(x=10,y=270)
    bt71 = Button(root,bd=0,image = x71)
    bt71.place(x=75,y=270)    
    bt70 = Button(root,bd=0,image = x70)
    bt70.place(x=140,y=270)
    bt69 = Button(root,bd=0,image = x69)
    bt69.place(x=205,y=270)    
    bt68 = Button(root,bd=0,image = x68)
    bt68.place(x=270,y=270)
    bt67 = Button(root,bd=0,image = x67)
    bt67.place(x=335,y=270)    
    bt66 = Button(root,bd=0,image = x66)
    bt66.place(x=400,y=270)
    bt65 = Button(root,bd=0,image = x65)
    bt65.place(x=465,y=270)  
    bt64 = Button(root,bd=0,image = x64)
    bt64.place(x=530,y=270)
    bt63 = Button(root,bd=0,image = x63)
    bt63.place(x=595,y=270)    
    bt62 = Button(root,bd=0,image = x62)
    bt62.place(x=660,y=270)
    bt61 = Button(root,bd=0,image = x61)
    bt61.place(x=725,y=270)    
#-
    bt60 = Button(root,bd=0,image = x60)
    bt60.place(x=10,y=335)
    bt59 = Button(root,bd=0,image = x59)
    bt59.place(x=75,y=335)    
    bt58 = Button(root,bd=0,image = x58)
    bt58.place(x=140,y=335)
    bt57 = Button(root,bd=0,image = x57)
    bt57.place(x=205,y=335)    
    bt56 = Button(root,bd=0,image = x56)
    bt56.place(x=270,y=335)
    bt55 = Button(root,bd=0,image = x55)
    bt55.place(x=335,y=335)   
    bt54 = Button(root,bd=0,image = x54)
    bt54.place(x=400,y=335)
    bt53 = Button(root,bd=0,image = x53)
    bt53.place(x=465,y=335)  
    bt52 = Button(root,bd=0,image = x52)
    bt52.place(x=530,y=335)
    bt51 = Button(root,bd=0,image = x51)
    bt51.place(x=595,y=335)    
    bt50 = Button(root,bd=0,image = x50)
    bt50.place(x=660,y=335)
    bt49 = Button(root,bd=0,image = x49)
    bt49.place(x=725,y=335)    
#-
    bt48 = Button(root,bd=0,image = x48)
    bt48.place(x=10,y=400)
    bt47 = Button(root,bd=0,image = x47)
    bt47.place(x=75,y=400)  
    bt46 = Button(root,bd=0,image = x46)
    bt46.place(x=140,y=400)
    bt45 = Button(root,bd=0,image = x45)
    bt45.place(x=205,y=400)    
    bt44 = Button(root,bd=0,image = x44)
    bt44.place(x=270,y=400)
    bt43 = Button(root,bd=0,image = x43)
    bt43.place(x=335,y=400)   
    bt42 = Button(root,bd=0,image = x42)
    bt42.place(x=400,y=400)
    bt41 = Button(root,bd=0,image = x41)
    bt41.place(x=465,y=400)  
    bt40 = Button(root,bd=0,image = x40)
    bt40.place(x=530,y=400)
    bt39 = Button(root,bd=0,image = x39)
    bt39.place(x=595,y=400)    
    bt38 = Button(root,bd=0,image = x38)
    bt38.place(x=660,y=400)
    bt37 = Button(root,bd=0,image = x37)
    bt37.place(x=725,y=400)    
#-
    bt36 = Button(root,bd=0,image = x36)
    bt36.place(x=10,y=465)
    bt35 = Button(root,bd=0,image = x35)
    bt35.place(x=75,y=465)    
    bt34 = Button(root,bd=0,image = x34)
    bt34.place(x=140,y=465)
    bt33 = Button(root,bd=0,image = x33)
    bt33.place(x=205,y=465)    
    bt32 = Button(root,bd=0,image = x32)
    bt32.place(x=270,y=465)
    bt31 = Button(root,bd=0,image = x31)
    bt31.place(x=335,y=465)   
    bt30 = Button(root,bd=0,image = x30)
    bt30.place(x=400,y=465)
    bt29 = Button(root,bd=0,image = x29)
    bt29.place(x=465,y=465)  
    bt28 = Button(root,bd=0,image = x28)
    bt28.place(x=530,y=465)
    bt27 = Button(root,bd=0,image = x27)
    bt27.place(x=595,y=465)    
    bt26 = Button(root,bd=0,image = x26)
    bt26.place(x=660,y=465)
    bt25 = Button(root,bd=0,image = x25)
    bt25.place(x=725,y=465)    
    #-
    bt24 = Button(root,bd=0,image = x24)
    bt24.place(x=10,y=530)
    bt23 = Button(root,bd=0,image = x23)
    bt23.place(x=75,y=530)    
    bt22 = Button(root,bd=0,image = x22)
    bt22.place(x=140,y=530)
    bt21 = Button(root,bd=0,image = x21)
    bt21.place(x=205,y=530)    
    bt20 = Button(root,bd=0,image = x20)
    bt20.place(x=270,y=530)
    bt19 = Button(root,bd=0,image = x19)
    bt19.place(x=335,y=530)   
    bt18 = Button(root,bd=0,image = x18)
    bt18.place(x=400,y=530)
    bt17 = Button(root,bd=0,image = x17)
    bt17.place(x=465,y=530)  
    bt16 = Button(root,bd=0,image = x16)
    bt16.place(x=530,y=530)
    bt15 = Button(root,bd=0,image = x15)
    bt15.place(x=595,y=530)    
    bt14 = Button(root,bd=0,image = x14)
    bt14.place(x=660,y=530)
    bt13 = Button(root,bd=0,image = x13)
    bt13.place(x=725,y=530)    
#-
    bt12 = Button(root,bd=0,image = x12)
    bt12.place(x=10,y=595)
    bt11 = Button(root,bd=0,image = x11)
    bt11.place(x=75,y=595)    
    bt10 = Button(root,bd=0,image = x10)
    bt10.place(x=140,y=595)
    bt9 = Button(root,bd=0,image = x9)
    bt9.place(x=205,y=595)    
    bt8 = Button(root,bd=0,image = x8)
    bt8.place(x=270,y=595)
    bt7 = Button(root,bd=0,image = x7)
    bt7.place(x=335,y=595)   
    bt6 = Button(root,bd=0,image = x6)
    bt6.place(x=400,y=595)
    bt5 = Button(root,bd=0,image = x5)
    bt5.place(x=465,y=595)  
    bt4 = Button(root,bd=0,image = x4)
    bt4.place(x=530,y=595)
    bt3 = Button(root,bd=0,image = x3)
    bt3.place(x=595,y=595)    
    bt2 = Button(root,bd=0,image = x2)
    bt2.place(x=660,y=595)
    bt1 = Button(root,bd=0,image = x1)
    bt1.place(x=725,y=595)      
    
    
    root.mainloop()

tk_run()