from tkinter import *


def tk_run():
    root = Tk()
    root.title("GUI")
    root.geometry("1980x1080")
    root.iconbitmap('')

    x120 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\120.png")
    x119 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\119.png")
    x118 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\118.png")
    x117 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\117.png")
    x116 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\116.png")
    x115 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\115.png")
    x114 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\114.png")
    x113 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\113.png")
    x112 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\112.png")
    x111 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\111.png")
    x110 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\110.png")
    x109 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\109.png")
    #-
    x108 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\108.png")
    x107 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\107.png")
    x106 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\106.png")
    x105 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\105.png")
    x104 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\104.png")
    x103 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\103.png")
    x102 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\102.png")
    x101 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\101.png")
    x100 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\100.png")
    x99 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\99.png")
    x98 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\98.png")
    x97 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\97.png")
    #-
    x96 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\96.png")
    x95 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\95.png")
    x94 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\94.png")
    x93 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\93.png")
    x92 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\92.png")
    x91 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\91.png")
    x90 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\90.png")
    x89 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\89.png")
    x88 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\88.png")
    x87 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\87.png")
    x86 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\86.png")
    x85 = PhotoImage(file="C:\\Users\\Siddhant Budhia\\OneDrive\\Documents\\GitHub\\NeevHacks2022\\GUI\\full_dirty_puzzle_fixed\\85.png")
 
    

    itemname = Label(root,text = "lols",font = ("courier new",30))
    itemname.place(x=1000,y=10)


    bt120 = Button(root,bd=0,image = x120)
    bt120.place(x=10,y=10)
    bt119 = Button(root,bd=0,image = x119)
    bt119.place(x=75,y=10)    
    bt118 = Button(root,bd=0,image = x118)
    bt118.place(x=140,y=10)
    bt117 = Button(root,bd=0,image = x117)
    bt117.place(x=205,y=10)    
    bt116 = Button(root,bd=0,image = x116)
    bt116.place(x=270,y=10)
    bt115 = Button(root,bd=0,image = x115)
    bt115.place(x=335,y=10)    
    bt114 = Button(root,bd=0,image = x114)
    bt114.place(x=400,y=10)
    bt113 = Button(root,bd=0,image = x113)
    bt113.place(x=465,y=10)  
    bt112 = Button(root,bd=0,image = x112)
    bt112.place(x=530,y=10)
    bt111 = Button(root,bd=0,image = x111)
    bt111.place(x=595,y=10)    
    bt110 = Button(root,bd=0,image = x110)
    bt110.place(x=660,y=10)
    bt109 = Button(root,bd=0,image = x109)
    bt109.place(x=725,y=10)   
    #-
    bt108 = Button(root,bd=0,image = x108)
    bt108.place(x=10,y=75)
    bt107 = Button(root,bd=0,image = x107)
    bt107.place(x=75,y=75)    
    bt106 = Button(root,bd=0,image = x106)
    bt106.place(x=140,y=75)
    bt105 = Button(root,bd=0,image = x105)
    bt105.place(x=205,y=75)    
    bt104 = Button(root,bd=0,image = x104)
    bt104.place(x=270,y=75)
    bt103 = Button(root,bd=0,image = x103)
    bt103.place(x=335,y=75)    
    bt102 = Button(root,bd=0,image = x102)
    bt102.place(x=400,y=75)
    bt101 = Button(root,bd=0,image = x101)
    bt101.place(x=465,y=75)  
    bt100 = Button(root,bd=0,image = x100)
    bt100.place(x=530,y=75)
    bt99 = Button(root,bd=0,image = x99)
    bt99.place(x=595,y=75)    
    bt98 = Button(root,bd=0,image = x98)
    bt98.place(x=660,y=75)
    bt97 = Button(root,bd=0,image = x97)
    bt97.place(x=725,y=75)   
    
    
    
    root.mainloop()

tk_run()